sim_portfolio_default:
    pattern: /
    defaults: { _controller: SimPortfolioBundle:Default:index }

sim_portfolio_project:
    pattern:  /project/{slug}
    defaults: { _controller: SimPortfolioBundle:Project:project }
