<?php

namespace Sim\CoreBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends RepositoryAbstract {

    /**
     * @param string $slug
     * @return Article
     */
    public function getBySlug($slug) {
        $queryBuilder = $this->getBaseSelectQueryBuilder();
        $queryBuilder->where($this->getEntityAlias() . '.slug = :slug');
        $queryBuilder->setParameter('slug', $slug);
        
        return $this->executeQueryBuilderForOne($queryBuilder);
    }

}
