<?php

namespace Sim\CoreBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends RepositoryAbstract
{
}
