<?php

namespace Sim\CoreBundle\Entity;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends RepositoryAbstract
{
}
