<?php

namespace Sim\CoreBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends RepositoryAbstract {
    
}
