sim_admin_homepage:
    pattern:  /
    defaults: { _controller: SimAdminBundle:Default:index }
    
sim_admin_portfolio:
    pattern:  /portfolio
    defaults: { _controller: SimAdminBundle:Portfolio:index }
